/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rewardTokenSol from "./RewardToken.sol";
export type { rewardTokenSol };
import type * as stackingCoreSol from "./StackingCore.sol";
export type { stackingCoreSol };
